"""Tengentoppa-sft-v1.0 から、長い回答 9,000件と短い回答 3,000件を取り出して学習データを作る。

蒸留後の Qwen3.5-0.8B（qwen08b-distill）は、学習データがほぼすべて長文（中央値 約1,900字）だったため、
どんな質問にも長く書き、長く書くほど話が破綻していた。質問に合った長さで答えることを教えるため、
短い回答を混ぜる（長文 3 : 短文 1）。

元データ：DeL-TaiseiOzaki/Tengentoppa-sft-v1.0（CC BY 4.0、revision 781a718ac17e070fb0135c5dbc3ac9ae7790758a）。
日本語の指示データ16〜17個を統合したもので、行ごとの出どころの列はない。

除くもの:
- 続きの文脈（input）がある行、指示が長すぎる行
- 評価用の質問に似た指示（文字の2-gram の重なり）、AI の感情・正体を問う指示
- 回答に中国語（日本語では使わない簡体字）、AI としての自己認識・感情の否定、電話番号・住所・外部 URL・メールアドレスを含む行
- 「申し訳ありませんが」で始まる回答（できないことの説明が中心で、会話の受け答えの例にならない）
- 同じ指示の重複

使い方:
    python3 sft/build_tengentoppa.py   # sft/tengentoppa_train.jsonl（12,000件）と sft/tengentoppa_valid.jsonl（200件）
    python3 sft/build_tengentoppa.py --clean   # 公開用：利用条件がはっきりした元データの行だけから選ぶ（sft/tengentoppa_clean_*.jsonl）
    python3 sft/build_tengentoppa.py --clean --pool 2   # 採点で選ぶ用に、学習の候補を2倍集める（sft/tengentoppa_clean_pool.jsonl）

--clean では、sft/map_tengentoppa_sources.py で調べた出どころを使い、次の元データの行だけを使う（CLEAN_SOURCES）。
除くもの：ライセンスの記載がない AutoGeneratedJapaneseQA-CC（Common Crawl から生成）、回答を作ったモデルが不明な
Aratako/SFT-Dataset-For-Self-Taught-Evaluators-iter1、元の記事が CC BY-NC-SA の wikiHow である WikiHowNFQA-ja、
出どころを特定できなかった行（アクセスに同意が必要な元データから来たと考えられる）。
あわせて、回答者が自分を人間だと言う行も除く（人が書いた会話データの影響で、学習後のモデルが「私は人間です」と答えたため）。

--pool では、同じ順番・同じ条件で候補を多めに集める。検証データと、先頭の 9,000 / 3,000 件（無作為に選んだ版の学習データ）は
--pool なしと同じになるので、Gemma の点数で選んだ版（sft/score_data_modal.py）と無作為の版をそのまま比べられる。
"""

import json
import random
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "eval"))
sys.path.insert(0, str(ROOT / "sft"))
from build_distill_prompts import EXCLUDE, bigrams  # noqa: E402
from build_distill_release import reason  # noqa: E402
from score import AI_SELF, DENY_FEELINGS, ZH_CHAR  # noqa: E402

SRC = ROOT / "data" / "tengentoppa" / "processed_dataset.json"
# 利用条件を確認できた元データ（ライセンスと、回答を作ったモデル）
CLEAN_SOURCES = {
    "llm-jp/magpie-sft-v1.0",                                   # Apache 2.0。質問 calm3-22b-chat、回答 Qwen2.5-32B-Instruct
    "DeL-TaiseiOzaki/Tengentoppa-sft-qwen2.5-32b-reasoning-100k",  # Apache 2.0。Qwen2.5-32B-Instruct
    "fujiki/japanese_hh-rlhf-49k",                              # MIT。Anthropic/hh-rlhf（MIT）の日本語訳
    "GENIAC-Team-Ozaki/JaGovFaqs-22k",                          # Apache 2.0。官公庁の FAQ
    "DeL-TaiseiOzaki/magpie-llm-jp-3-13b-20k",                  # Apache 2.0。llm-jp-3-13b-instruct
    "GENIAC-Team-Ozaki/oasst2-33k-ja_reformatted",              # Apache 2.0。OpenAssistant の日本語訳
    "GENIAC-Team-Ozaki/chatbot-arena-ja-karakuri-lm-8x7b-chat-v0.1-awq",  # CC BY 4.0。回答 karakuri-lm-8x7b-chat（Apache 2.0）
    "GENIAC-Team-Ozaki/Hachi-Alpaca_newans",                    # CC BY 4.0。Mixtral-8x22B-Instruct（Apache 2.0）
    "GENIAC-Team-Ozaki/Evol-Alpaca-gen3-500_cleaned",           # Apache 2.0
    "GENIAC-Team-Ozaki/Evol-hh-rlhf-gen3-1k_cleaned",           # Apache 2.0
    "GENIAC-Team-Ozaki/debate_argument_instruction_dataset_ja", # Apache 2.0
}
HUMAN_CLAIM = re.compile(r"私は(おそらく)?人間|人間である私|僕は人間|私も人間")
N_LONG, N_SHORT = 9000, 3000
N_VALID_LONG, N_VALID_SHORT = 150, 50
LONG = (400, 2000)   # 回答の文字数
SHORT = (20, 200)
KANA = re.compile(r"[ぁ-んァ-ン]")
END = re.compile(r"[。！？!?」』）)♪～〜…w]$")


def main():
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--clean", action="store_true", help="利用条件を確認できた元データの行だけを使う（公開用）")
    ap.add_argument("--pool", type=int, default=1, help="学習の候補を何倍集めるか（2以上で tengentoppa_*pool.jsonl に書き出す）")
    args = ap.parse_args()
    rng = random.Random(0)
    rows = json.loads(SRC.read_text())
    sources = json.loads((ROOT / "data" / "tengentoppa" / "row_sources_full.json").read_text()) if args.clean else None
    eval_bg = [bigrams(it["prompt"]) for it in json.loads((ROOT / "eval" / "prompts.json").read_text())["items"]]
    order = list(range(len(rows)))
    rng.shuffle(order)

    need = {"long": N_LONG * args.pool + N_VALID_LONG, "short": N_SHORT * args.pool + N_VALID_SHORT}
    picked = {"long": [], "short": []}
    seen, dropped = set(), Counter()
    for i in order:
        if all(len(picked[k]) >= need[k] for k in need):
            break
        r = rows[i]
        ins, out = (r.get("instruction") or "").strip(), (r.get("output") or "").strip()
        n = len(out)
        kind = "long" if LONG[0] <= n <= LONG[1] else "short" if SHORT[0] <= n <= SHORT[1] else None
        if kind is None or len(picked[kind]) >= need[kind]:
            continue
        if sources is not None and not set(sources[i].split(",")) <= CLEAN_SOURCES:
            dropped["source"] += 1
        elif sources is not None and HUMAN_CLAIM.search(out):
            dropped["human_claim"] += 1
        elif (r.get("input") or "").strip():
            dropped["input"] += 1
        elif not (5 <= len(ins) <= 800) or ins in seen:
            dropped["instruction"] += 1
        elif EXCLUDE.search(ins):
            dropped["ai_question"] += 1
        elif not KANA.search(out) or ZH_CHAR.search(ins + out):
            dropped["language"] += 1
        elif AI_SELF.search(out) or DENY_FEELINGS.search(out):
            dropped["ai_self"] += 1
        elif out.startswith("申し訳"):
            dropped["apology"] += 1
        elif reason(ins + "\n" + out):
            dropped["contact_info"] += 1
        elif kind == "short" and not END.search(out):
            dropped["short_unfinished"] += 1
        elif any(len(bigrams(ins) & e) / max(1, len(bigrams(ins) | e)) > 0.3 for e in eval_bg):
            dropped["like_eval"] += 1
        else:
            seen.add(ins)
            picked[kind].append({"messages": [{"role": "user", "content": ins}, {"role": "assistant", "content": out}],
                                 "dataset": "tengentoppa", "kind": kind, "source_row": i,
                                 **({"source": sources[i]} if sources is not None else {})})

    prefix = "clean_" if args.clean else ""
    if args.pool > 1:
        pool = picked["long"][N_VALID_LONG:] + picked["short"][N_VALID_SHORT:]
        (ROOT / "sft" / f"tengentoppa_{prefix}pool.jsonl").write_text("".join(json.dumps(x, ensure_ascii=False) + "\n" for x in pool))
        print(f"候補 {len(pool)} 件（長文 {len(picked['long']) - N_VALID_LONG} / 短文 {len(picked['short']) - N_VALID_SHORT}）")
        return
    train = picked["long"][N_VALID_LONG:] + picked["short"][N_VALID_SHORT:]
    valid = picked["long"][:N_VALID_LONG] + picked["short"][:N_VALID_SHORT]
    rng.shuffle(train)
    for name, data in (("train", train), ("valid", valid)):
        (ROOT / "sft" / f"tengentoppa_{prefix}{name}.jsonl").write_text("".join(json.dumps(x, ensure_ascii=False) + "\n" for x in data))
    lens = {k: sorted(len(x["messages"][1]["content"]) for x in v) for k, v in picked.items()}
    print(f"学習 {len(train)} 件（長文 {N_LONG} / 短文 {N_SHORT}）、検証 {len(valid)} 件")
    print(f"回答の文字数の中央値：長文 {lens['long'][len(lens['long']) // 2]}、短文 {lens['short'][len(lens['short']) // 2]}")
    print(f"除外 {dict(dropped)}")
    if sources is not None:
        print("元データ", dict(Counter(x["source"] for x in train + valid).most_common()))


if __name__ == "__main__":
    main()
